/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animacionpelota;

import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Erickquillo
 */
public class lienzo extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form lienzo
     */
    Thread hilo;

    int x = getWidth() / 2;
    int y = 0;
    int control;

    public lienzo() {
        initComponents();
        hilo = new Thread(this);

    }

    public void paint(Graphics g) {
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.BLUE);
        g.fillOval(x, getHeight() / 2, 30, 30);
        g.setColor(Color.BLACK);
        g.fillOval(5, x, 30, 30);
        g.setColor(Color.CYAN);
        g.fillOval(x, x / 3, 30, 30);

      

    }

    public void inicio() {
        hilo.start();
    }

    public void pausa() {
        hilo.suspend();
    }

    public void continuar() {
        hilo.resume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {

        while (true) {
            while (x < getWidth() - 30) {
                try {
                    Thread.sleep(100);
                    x += 10;

                    repaint();
                } catch (InterruptedException ex) {
                    Logger.getLogger(lienzo.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            while (true) {
                while (x > 10) {
                    try {
                        Thread.sleep(100);
                        x -= 10;

                        repaint();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(lienzo.class.getName()).log(Level.SEVERE, null, ex);


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
                    }
                }
            }
        }

    }
}
